### ISSUE TITLE
docker-compose up failing because "port is already allocated" 

### ISSUE THREAD

**Issue by Syauri** [NLPbox/dplp-service#2]
Creating network "dplp-service_default" with the default driver
Creating dplp-service_corenlp_1      ... error
Creating dplp-service_dplp-service_1 ... 

ERROR: for dplp-service_corenlp_1  Cannot start service corenlp: driver failed programming external connectivity on endpoint dplp-service_corenlp_1 (39a9a7577b22d42e9014900e862573d70Creating dplp-service_dplp-service_1 ... done

ERROR: for corenlp  Cannot start service corenlp: driver failed programming external connectivity on endpoint dplp-service_corenlp_1 (39a9a7577b22d42e9014900e862573d700abf3440f251e8e983c1e2c35e2c62e): Bind for 0.0.0.0:9000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by arne-cl** [comment]
Dear Shreeya,

the error ``Bind for 0.0.0.0:9000 failed: port is already allocated`` usually occurs when there is
already some service running on your computer on that port. It could well be that this is a docker container that you've started earlier. You can check which containers are running with ``docker ps``
and stop containers with ``docker stop``.

**Comment by Syauri** [comment]
Thank you! This is what I am getting now. It does not go past this:

dplp-service_corenlp_1 is up-to-date
dplp-service_dplp-service_1 is up-to-date
Attaching to dplp-service_corenlp_1, dplp-service_dplp-service_1
corenlp_1       | [main] INFO CoreNLP - --- StanfordCoreNLPServer#main() called ---
corenlp_1       | [main] INFO CoreNLP - setting default constituency parser
corenlp_1       | [main] INFO CoreNLP - using SR parser: edu/stanford/nlp/models/srparser/englishSR.ser.gz
corenlp_1       | [main] INFO CoreNLP -     Threads: 2
corenlp_1       | [main] INFO CoreNLP - Starting server...
corenlp_1       | [main] INFO CoreNLP - StanfordCoreNLPServer listening at /0.0.0.0:9000
corenlp_1       | [pool-1-thread-1] INFO CoreNLP - [/172.19.0.3:60148] API call w/annotators tokenize,ssplit,pos,lemma,ner,parse
corenlp_1       | Altough they didn't like him, they accepted the offer.
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator tokenize
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ssplit
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator pos
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [3.6 sec].
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator lemma
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator ner
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.all.3class.distsim.crf.ser.gz ... done [3.4 sec].
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.muc.7class.distsim.crf.ser.gz ... done [2.3 sec].
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.ie.AbstractSequenceClassifier - Loading classifier from edu/stanford/nlp/models/ner/english.conll.4class.distsim.crf.ser.gz ... done [3.4 sec].
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.time.JollyDayHolidays - Initializing JollyDayHoliday for SUTime from classpath edu/stanford/nlp/models/sutime/jollyday/Holidays_sutime.xml as sutime.binder.1.
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.time.TimeExpressionExtractorImpl - Using following SUTime rules: edu/stanford/nlp/models/sutime/defs.sutime.txt,edu/stanford/nlp/models/sutime/english.sutime.txt,edu/stanford/nlp/models/sutime/english.holidays.sutime.txt
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 580704 unique entries out of 581863 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_caseless.tab, 0 TokensRegex patterns.
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 4869 unique entries out of 4869 from edu/stanford/nlp/models/kbp/english/gazetteers/regexner_cased.tab, 0 TokensRegex patterns.
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.TokensRegexNERAnnotator - ner.fine.regexner: Read 585573 unique entries from 2 files
corenlp_1       | [pool-1-thread-1] INFO edu.stanford.nlp.pipeline.StanfordCoreNLP - Adding annotator parse
dplp-service_corenlp_1 exited with code 137
dplp-service_1  | Traceback (most recent call last):
dplp-service_1  |   File "/usr/lib/python3.5/wsgiref/handlers.py", line 137, in run
dplp-service_1  |     self.result = application(self.environ, self.start_response)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/falcon/api.py", line 244, in __call__
dplp-service_1  |     responder(req, resp, **params)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/hug/interface.py", line 793, in __call__
dplp-service_1  |     raise exception
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/hug/interface.py", line 766, in __call__
dplp-service_1  |     self.render_content(self.call_function(input_parameters), context, request, response, **kwargs)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/hug/interface.py", line 703, in call_function
dplp-service_1  |     return self.interface(**parameters)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/hug/interface.py", line 100, in __call__
dplp-service_1  |     return __hug_internal_self._function(*args, **kwargs)
dplp-service_1  |   File "dplp_hug_api.py", line 35, in call_parser
dplp-service_1  |     parser_stdout = parser(input_file.name, _cwd=PARSER_PATH)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/sh.py", line 1427, in __call__
dplp-service_1  |     return RunningCommand(cmd, call_args, stdin, stdout, stderr)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/sh.py", line 774, in __init__
dplp-service_1  |     self.wait()
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/sh.py", line 792, in wait
dplp-service_1  |     self.handle_command_exit_code(exit_code)
dplp-service_1  |   File "/usr/local/lib/python3.5/dist-packages/sh.py", line 815, in handle_command_exit_code
dplp-service_1  |     raise exc
dplp-service_1  | sh.ErrorReturnCode_1: 
dplp-service_1  | 
dplp-service_1  |   RAN: /opt/DPLP/dplp.sh /tmp/input.txt
dplp-service_1  | 
dplp-service_1  |   STDOUT:
dplp-service_1  | Could not parse input file ...
dplp-service_1  | Calling CoreNLP resulted in this error: ('Connection aborted.', BadStatusLine("''",))
dplp-service_1  | 
dplp-service_1  | 
dplp-service_1  |   STDERR:
dplp-service_1  |

**Comment by arne-cl** [comment]
CoreNLP is crashing before dplp-service even calls it: 
``dplp-service_corenlp_1 exited with code 137``

I don't know why this happens, as there are no further error messages from this container. If its not important to you which RST parser you are using, you can try one of these instead:

https://github.com/NLPbox/feng-hirst-service (Feng and Hirst 2014)
https://github.com/NLPbox/codra-service (Joty et al. 2015)
https://github.com/NLPbox/heilman-sagae-2015-service

If you need to use DPLP, you might try a few things:

1. check if you have enough RAM (CoreNLP alone uses 4GB)
2. try running `docker-compose up --build --force-recreate` instead of `docker-compose up`
3. use a different version of CoreNLP by replacing the version string in `docker-compose.yml`
    from `3.9.2` to one of `3.6.0`, `3.7.0`, `3.8.0`, `3.9.1` .
4. install and run [CoreNLP server](https://stanfordnlp.github.io/CoreNLP/corenlp-server.html)
    manually on your machine on port 9000 and run

```
docker build -t dplp-service .
docker container run -e "CORENLP_ENDPOINT=http://DOCKER_HOST:9000" -p 9001:8000 -ti dplp-service
```

where `DOCKER_HOST` is the [hostname](https://nickjanetakis.com/blog/docker-tip-65-get-your-docker-hosts-ip-address-from-in-a-container) of your computer as seen from within the `dplp-service` container.
